# Generated by Django 5.2.1 on 2025-06-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='carreras',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='usuarios',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
