# Generated by Django 5.2.1 on 2025-06-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_alter_comunidad_carreras_alter_comunidad_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='url_descarga',
        ),
    ]
