# Generated by Django 5.2.1 on 2025-07-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0004_noticia_servicioalumni_testimonio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del curso', null=True),
        ),
    ]
