# Generated by Django 5.2.1 on 2025-07-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0005_alter_curso_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha de finalización del curso (opcional)', null=True),
        ),
    ]
