# Generated by Django 5.2.1 on 2025-07-04 00:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0006_alter_curso_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='carreras_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='usuarios_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='documento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
