# Generated by Django 5.2.1 on 2025-07-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0007_comunidad_carreras_array_comunidad_usuarios_array_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='carreras',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='usuarios',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
