# Generated by Django 5.2.1 on 2025-07-04 00:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0008_alter_comunidad_carreras_alter_comunidad_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='carreras_array',
        ),
        migrations.RemoveField(
            model_name='comunidad',
            name='usuarios_array',
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='carreras',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='usuarios',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
