# Generated by Django 5.2.1 on 2025-07-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0009_remove_comunidad_carreras_array_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='carreras',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='usuarios',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
