# Generated by Django 5.2.1 on 2025-07-04 01:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0011_alter_evento_carreras_alter_evento_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='carreras',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
