# Generated by Django 5.2.1 on 2025-07-04 01:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0012_alter_evento_carreras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='carreras',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
