# Generated by Django 5.2.1 on 2025-07-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0013_alter_comunidad_carreras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='inscritos',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
