# Generated by Django 5.2.1 on 2025-07-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0014_alter_curso_inscritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='inscritos',
            field=models.TextField(blank=True, help_text='Lista de IDs de usuarios inscritos (separados por comas)', null=True),
        ),
    ]
