# Generated by Django 5.2.1 on 2025-07-04 02:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0015_alter_curso_inscritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='inscritos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
