# Generated by Django 5.2.1 on 2025-07-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0016_alter_curso_inscritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tipo_carrera',
            field=models.CharField(choices=[('INGSIS', 'Ingeniería de Sistemas'), ('INGCOM', 'Ingeniería Comercial'), ('DER', 'Derecho'), ('PSI', 'Psicología'), ('ENF', 'Enfermería'), ('MED', 'Medicina'), ('CP', 'Contaduría Pública'), ('ADM', 'Administración de Empresas'), ('INGELEC', 'Ingeniería Electrónica'), ('ARQ', 'Arquitectura'), ('SIN', 'Sin Especificar')], default='SIN', max_length=50),
        ),
    ]
