# Generated by Django 5.2.1 on 2025-07-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0017_documento_tipo_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='comunidades/'),
        ),
    ]
