# Generated by Django 5.2.1 on 2025-07-04 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0018_comunidad_imagen_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_id', models.IntegerField()),
                ('contenido', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='mensajes_archivos/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mensajes_imagenes/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='Content.comunidad')),
            ],
            options={
                'ordering': ['fecha_envio'],
            },
        ),
    ]
