# Generated by Django 6.0.2 on 2026-03-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0019_mensajecomunidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.RemoveField(
            model_name='documento',
            name='tipo_carrera',
        ),
        migrations.AddField(
            model_name='documento',
            name='carrera',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='documento',
            table='documento',
        ),
    ]
