# Generated by Django 6.0.2 on 2026-03-06 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0020_alter_documento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonio',
            options={'ordering': ['-fecha'], 'verbose_name': 'Testimonio', 'verbose_name_plural': 'Testimonios'},
        ),
        migrations.RemoveField(
            model_name='testimonio',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='testimonio',
            name='autor',
            field=models.CharField(default='Anónimo', max_length=255),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
