# Generated by Django 6.0.2 on 2026-03-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0021_alter_testimonio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
