# Generated by Django 6.0.2 on 2026-03-09 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0022_comunidad_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='conversaciones/')),
                ('creador_id', models.IntegerField()),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cerrado_por_id', models.IntegerField(blank=True, null=True)),
                ('ultimo_mensaje_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conversación de comunidad',
                'verbose_name_plural': 'Conversaciones de comunidad',
                'db_table': 'conversacion_comunidad',
                'ordering': ['-ultimo_mensaje_at', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MensajeConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_id', models.IntegerField()),
                ('contenido', models.TextField(blank=True, default='')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='mensajes_conversacion/archivos/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mensajes_conversacion/imagenes/')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('editado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mensaje de conversación',
                'verbose_name_plural': 'Mensajes de conversación',
                'db_table': 'mensaje_conversacion',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.AddField(
            model_name='comunidad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
        migrations.AddIndex(
            model_name='comunidad',
            index=models.Index(fields=['slug'], name='comunidad_slug_d0f38a_idx'),
        ),
        migrations.AddIndex(
            model_name='comunidad',
            index=models.Index(fields=['activo'], name='comunidad_activo_f8d7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='comunidad',
            index=models.Index(fields=['fecha_creacion'], name='comunidad_fecha_c_4fd7f4_idx'),
        ),
        migrations.AddIndex(
            model_name='comunidad',
            index=models.Index(fields=['fecha_actualizacion'], name='comunidad_fecha_a_193ef7_idx'),
        ),
        migrations.AddField(
            model_name='conversacioncomunidad',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='Content.comunidad'),
        ),
        migrations.AddField(
            model_name='mensajeconversacion',
            name='conversacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='Content.conversacioncomunidad'),
        ),
        migrations.AddIndex(
            model_name='conversacioncomunidad',
            index=models.Index(fields=['comunidad'], name='conversacio_comunid_45b1e2_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacioncomunidad',
            index=models.Index(fields=['estado'], name='conversacio_estado_b6bbe2_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacioncomunidad',
            index=models.Index(fields=['activa'], name='conversacio_activa_30fb7d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacioncomunidad',
            index=models.Index(fields=['fecha_creacion'], name='conversacio_fecha_c_8b0b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacioncomunidad',
            index=models.Index(fields=['ultimo_mensaje_at'], name='conversacio_ultimo__d17961_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversacioncomunidad',
            constraint=models.UniqueConstraint(fields=('comunidad', 'slug'), name='uq_conversacion_comunidad_slug'),
        ),
        migrations.AddIndex(
            model_name='mensajeconversacion',
            index=models.Index(fields=['conversacion'], name='mensaje_con_convers_ffcc1f_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajeconversacion',
            index=models.Index(fields=['autor_id'], name='mensaje_con_autor_i_8a318c_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajeconversacion',
            index=models.Index(fields=['estado'], name='mensaje_con_estado_824bba_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajeconversacion',
            index=models.Index(fields=['fecha_envio'], name='mensaje_con_fecha_e_667ead_idx'),
        ),
    ]
