# Generated by Django 6.0.2 on 2026-03-09 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0023_conversacioncomunidad_mensajeconversacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-destacado', 'orden', '-fecha_publicacion'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AddField(
            model_name='noticia',
            name='actualizado_por_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='boton_texto',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='noticia',
            name='boton_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='noticia',
            name='comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='Content.comunidad'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='creado_por_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noticia',
            name='destino',
            field=models.CharField(choices=[('HOME', 'Home'), ('COMUNIDAD', 'Comunidad')], default='HOME', max_length=20),
        ),
        migrations.AddField(
            model_name='noticia',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias_relacionadas', to='Content.evento'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='fecha_fin_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='fecha_inicio_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='noticia',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='resumen',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
        migrations.AddField(
            model_name='noticia',
            name='tipo',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('BOTON', 'Normal con botón'), ('EVENTO', 'Normal con evento'), ('BOTON_EVENTO', 'Normal con botón y evento')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=220),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['destino'], name='noticia_destino_978881_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['publicado'], name='noticia_publica_1e8e77_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['destacado'], name='noticia_destaca_0be958_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['fecha_publicacion'], name='noticia_fecha_p_84d123_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['fecha_actualizacion'], name='noticia_fecha_a_7393fe_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['fecha_inicio_publicacion'], name='noticia_fecha_i_8e5943_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['fecha_fin_publicacion'], name='noticia_fecha_f_715499_idx'),
        ),
    ]
