"""
Django settings for ContenidoAlumniApi project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlparse, urlunparse
from django.core.management.commands.runserver import Command as runserver

import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Buscar .env en rutas típicas (proyecto, raíz, 2 niveles arriba)
CANDIDATES = [
    BASE_DIR / ".env",
    BASE_DIR.parent / ".env",
    BASE_DIR.parent.parent / ".env",
]

ENV_PATH = next((p for p in CANDIDATES if p.exists()), None)

if ENV_PATH is not None:
    load_dotenv(dotenv_path=ENV_PATH, override=False)

# Puerto (después de cargar env)
runserver.default_port = os.getenv("PORT", "8001")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-unsafe-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in (
    "1", "true", "yes", "y", "on"
)

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    "corsheaders",
    'channels',
    'rest_framework',
    'rest_framework_simplejwt',
    'Content'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ContenidoAlumniApi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'ContenidoAlumniApi.asgi.application'


REDIS_HOST = os.getenv("REDIS_HOST", "127.0.0.1")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", "")
REDIS_URL = os.getenv("REDIS_URL", "").strip()


def _is_true(value: str, default: bool = False) -> bool:
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "y", "on")


def _build_redis_url(host: str, port: int, password: str, db: int, use_ssl: bool) -> str:
    scheme = "rediss" if use_ssl else "redis"
    credentials = f":{password}@" if password else ""
    return f"{scheme}://{credentials}{host}:{port}/{db}"


def _override_redis_db(redis_url: str, db: int) -> str:
    parsed = urlparse(redis_url)
    if not parsed.scheme:
        return redis_url
    return urlunparse(parsed._replace(path=f"/{db}"))


if not REDIS_URL:
    redis_use_ssl_default = REDIS_HOST.endswith(".redis.cache.windows.net")
    redis_use_ssl = _is_true(os.getenv("REDIS_USE_SSL"), default=redis_use_ssl_default)
    REDIS_URL = _build_redis_url(
        host=REDIS_HOST,
        port=REDIS_PORT,
        password=REDIS_PASSWORD,
        db=0,
        use_ssl=redis_use_ssl,
    )

REDIS_CACHE_DB = int(os.getenv("REDIS_CACHE_DB", "1"))
REDIS_CHANNEL_DB = int(os.getenv("REDIS_CHANNEL_DB", "0"))
REDIS_CACHE_URL = os.getenv("REDIS_CACHE_URL", "").strip() or _override_redis_db(REDIS_URL, REDIS_CACHE_DB)
REDIS_CHANNEL_URL = os.getenv("REDIS_CHANNEL_URL", "").strip() or _override_redis_db(REDIS_URL, REDIS_CHANNEL_DB)

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_CHANNEL_URL],
        },
    },
}




# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "proxy_db"),
        "USER": os.getenv("DB_USER", "proxy_user"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (User-uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CORS settings
VAR_DJANGO_ALLOWED_ORIGINS = os.getenv("DJANGO_ALLOWED_ORIGINS", "http://localhost:5173,http://127.0.0.1:5173")
VAR_DJANGO_ALLOWED_ORIGINS = [origin.strip() for origin in VAR_DJANGO_ALLOWED_ORIGINS.split(",") if origin.strip()]

CORS_ALLOWED_ORIGINS = VAR_DJANGO_ALLOWED_ORIGINS

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

# Cache settings

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
        "OPTIONS": {
            "socket_connect_timeout": 3,
            "socket_timeout": 3,
        }
    }
}

# Authentication settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'Content.auth.JWTAuthentication',
    ]
}

# JWT settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# logging configuration

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "loggers": {
        "Content": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
