# Generated by Django 5.2.1 on 2025-06-02 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('INGSIS', 'Ingeniería de Sistemas'), ('INGCOM', 'Ingeniería Comercial'), ('DER', 'Derecho'), ('PSI', 'Psicología'), ('ENF', 'Enfermería'), ('MED', 'Medicina'), ('CP', 'Contaduría Pública'), ('ADM', 'Administración de Empresas'), ('INGELEC', 'Ingeniería Electrónica'), ('ARQ', 'Arquitectura')], max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'carrera',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UserAlumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Access.carrera')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Alumni',
                'verbose_name_plural': 'User Alumni',
                'db_table': 'user_alumni',
            },
        ),
    ]
